version: "3.8"

services:
  sneakydog-raspberrypi-demo:
    image: sneakydogs/sneakydog_raspberrypi_demo:latest
    container_name: sneakydog-raspberrypi-demo
    restart: always
    privileged: true
    networks:
      - traefik
    volumes:
      - /DATA/Gallery:/DATA/Gallery
      - /run/udev:/run/udev:ro
    devices:
      - /dev/video0:/dev/video0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sneakydog_respberrypi_demo.rule=Host(`raspberrypi`)"
      - "traefik.http.routers.sneakydog_respberrypi_demo.service=sneakydog_respberrypi_demo"
      - "traefik.http.services.sneakydog_respberrypi_demo.loadbalancer.server.scheme=http"
      - "traefik.http.services.sneakydog_respberrypi_demo.loadbalancer.server.port=5000"
    environment:
      - TZ=Asia/Shanghai
      - FLASK_APP=sneakydog_raspberrypi_demo
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=0


networks:
  traefik:
    external: true
