services:
  mysqldb:
    hostname: mysqldb
    image: mysql:8.4.1
    container_name: mysqldb
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: on-failure
    networks:
      - traefik
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "./conf.d/mysql.conf:/etc/mysql/conf.d/mysql.conf:rw"
      - "./datadir:/var/lib/mysql"

networks:
  traefik:
    external: true
